---
stages:
  - prepare
  - build
  - deploy

build-frontend:
  stage: prepare
  image: "node:8.11.2-slim"
  cache:
    paths:
      - node_modules
  before_script:
    - "apt-get update -qq && apt-get install -qq --yes python make g++"
  script:
    - yarn
    - yarn run gulp sass
    - yarn run webpack
  artifacts:
    paths:
      - static

build-content:
  stage: build
  image: "jojomi/hugo:0.41"
  script:
    - hugo
  artifacts:
    paths:
      - public

build-index:
  stage: build
  image: "registry.gitlab.com/zerok/zerokspot.com/blogsearch:latest"
  script:
    - "blogsearch -hugo $PWD -index ./search.bleve"
  artifacts:
    paths:
      - "search.bleve"

deploy:
  stage: deploy
  image: "registry.gitlab.com/zerok/zerokspot.com/rsync:latest"
  only:
    - master
  environment:
    name: Production
    url: https://zerokspot.com
  before_script:
    - "eval $(ssh-agent)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - "mkdir -p ~/.ssh && chmod 0700 ~/.ssh"
  script:
    - "rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz search.bleve www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/var/search/"
    - "cd public && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz * www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/htdocs/"
