---
stages:
  - prepare
  - build
  - index
  - deploy
  - mention

build-tools:
  stage: prepare
  image: "golang:1.13.3-alpine"
  script:
    - "cd cmd/blog && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../../blog && cd -"
    - "cd cmd/blogsearch && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../../blogsearch && cd -"
  artifacts:
    paths:
      - blog
      - blogsearch

build-frontend:
  stage: prepare
  image: "node:12-stretch-slim"
  cache:
    paths:
      - node_modules
  before_script:
    - "apt-get update -qq && apt-get install -qq --yes python make g++"
  script:
    - yarn
    - yarn run webpack
  artifacts:
    paths:
      - static

build-content:
  stage: build
  image: "jojomi/hugo:0.69.0"
  script:
    - hugo
    - ./blog build-graph
    - ./blog blogroll --output data/blogroll.json
    - hugo
  dependencies:
    - build-tools
    - build-frontend
  artifacts:
    paths:
      - public

index:
  stage: index
  image: "alpine:3.11"
  script:
    - "apk add git curl"
    - "./blogsearch update-index --updated-objects-path public/.updated-objects.txt"
    - "cat public/.updated-objects.txt"
    - "./blogsearch build-mapping"
    - "./blog changes --since-rev $(curl https://zerokspot.com/.gitrev) --url > public/.changes.txt"
    - "git rev-parse HEAD > public/.gitrev"
  dependencies:
    - build-tools
    - build-content
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: "registry.gitlab.com/zerok/zerokspot.com/rsync:latest"
  only:
    - master
  environment:
    name: Production
    url: https://zerokspot.com
  before_script:
    - "eval $(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - "mkdir -p ~/.ssh && chmod 0700 ~/.ssh"
  script:
    - "test -f blogsearch && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz blogsearch www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/bin/ || echo \"blogsearch not updated\""
    - "cd public && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz * .mapping.json.xz .gitrev www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/htdocs/"
    - "ssh www-zerokspot@zerokspot.com \"touch /srv/www/zerokspot.com/www/deployed\""

mention:
  stage: mention
  image:
    name: "zerok/webmentiond:latest"
    entrypoint:
      - /bin/ash
      - "-c"
  dependencies:
    - build-tools
    - deploy
    - index
  only:
    - master
  script:
    - "cat ./public/.changes.txt"
    - "(test $(stat -f '%b' ./public/.changes.txt) -gt 10) && (cat ./public/.changes.txt | xargs -n 1 /usr/local/bin/webmentiond send)"

