---
stages:
  - prepare
  - build
  - index
  - deploy

build-search-server:
  stage: prepare
  image: "golang:1.13.0-alpine"
  script:
    - "cd cmd/blogsearch && GOOS=linux GOARCH=amd64 go build -o ../../blogsearch && cd -"
    - "cd cmd/blog && GOOS=linux GOARCH=amd64 go build -o ../../blog && cd -"
  artifacts:
    paths:
      - blogsearch
      - blog

build-frontend:
  stage: prepare
  image: "node:8.15.1-stretch-slim"
  cache:
    paths:
      - node_modules
  before_script:
    - "apt-get update -qq && apt-get install -qq --yes python make g++"
  script:
    - yarn
    - yarn run gulp sass
    - yarn run webpack
  artifacts:
    paths:
      - static

build-content:
  stage: build
  image: "jojomi/hugo:0.41"
  script:
    - hugo
    - ./blog build-graph
    - hugo
  dependencies:
    - build-search-server
    - build-frontend
  artifacts:
    paths:
      - public

index:
  stage: index
  image: "registry.gitlab.com/zerok/zerokspot.com/blogsearch:latest"
  script:
    - "blogsearch update-index"
    - "blogsearch build-mapping"
    - "git rev-parse HEAD > public/.gitrev"
  dependencies:
    - build-content
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: "registry.gitlab.com/zerok/zerokspot.com/rsync:latest"
  only:
    - master
  environment:
    name: Production
    url: https://zerokspot.com
  before_script:
    - "eval $(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - "mkdir -p ~/.ssh && chmod 0700 ~/.ssh"
  script:
    - "test -f blogsearch && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz blogsearch www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/bin/ || echo \"blogsearch not updated\""
    - "cd public && rsync -e \"ssh -o StrictHostKeyChecking=no\" -avz * .mapping.json.xz .gitrev www-zerokspot@zerokspot.com:/srv/www/zerokspot.com/www/htdocs/"
    - "ssh www-zerokspot@zerokspot.com \"touch /srv/www/zerokspot.com/www/deployed\""
