baseurl = "https://zerokspot.com/"
languageCode = "en-us"
title = "zerokspot.com"
metaDataFormat = "yaml"
editor = "em -n"
ignoreFiles = [ "\\.\\#" ]
paginate = 10

[markup]
  defaultMarkdownHandler = "blackFriday"

[params]
mainSections = ["weblog", "notes"]

[permalinks]
weblog = "/weblog/:year/:month/:day/:filename/"
notes = "/notes/:year/:month/:day/:filename/"

[outputs]
weblog = ["html", "json", "rss"]
page = ["html", "json"]


