baseurl = "https://zerokspot.com/"
languageCode = "en-us"
title = "zerokspot.com"
metaDataFormat = "yaml"
editor = "em -n"
ignoreFiles = [ "\\.\\#" ]

[permalinks]
weblog = "/weblog/:year/:month/:day/:filename/"

[outputs]
page = ["html", "json"]


