name: CI

on: [push]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.2
      with:
        node-version: "12.x"
    - run: "sudo apt-get install -qq --yes python make g++"
    - run: "yarn"
    - run: "yarn run webpack"
    - uses: actions/upload-artifact@v1
      with:
        name: frontend
        path: static

  build-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1.1.1
      with:
        go-version: "1.13.1"
    - name: Build blogsearch
      run: "cd cmd/blogsearch && GOOS=linux GOARCH=amd64 go build -o ../../blogsearch && cd -"
    - name: Build CLI
      run: "cd cmd/blog && GOOS=linux GOARCH=amd64 go build -o ../../blog && cd -"
    - uses: actions/upload-artifact@v1
      with:
        name: blogcli
        path: blog
    - uses: actions/upload-artifact@v1
      with:
        name: blogsearch
        path: blogsearch

  build-content:
    needs:
      - build-tools
      - build-frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: 0.69.0
    - uses: actions/download-artifact@v1
      with:
        name: frontend
        path: static
    - uses: actions/download-artifact@v1
      with:
        name: blogcli
    - run: hugo
    - run: chmod +x ./blogcli/blog
    - run: ./blogcli/blog build-graph
    - run: ./blogcli/blog blogroll --output data/blogroll.json
    - run: hugo
    - uses: actions/upload-artifact@v1
      with:
        name: public
        path: public
